import { useState } from 'react';
import type { FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, Trash2 } from 'lucide-react';
import { materialsApi, type MaterialInput } from '../api/materials';
import { Button } from '../components/Button';
import { Card, CardContent } from '../components/Card';

const empty:MaterialInput={code:'',material:'PLA',subtype:'',brand:'',color_name:'',color_hex:'#FFFFFF',is_active:true};
export function MaterialTypesPage(){const qc=useQueryClient();const {data=[]}=useQuery({queryKey:['material-types'],queryFn:materialsApi.list});const [form,setForm]=useState(empty);const create=useMutation({mutationFn:materialsApi.create,onSuccess:()=>{qc.invalidateQueries({queryKey:['material-types']});setForm(empty)}});return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6"><div><h1 className="text-3xl font-bold text-white">材料类型</h1><p className="text-bambu-gray mt-1">统一品牌、材料、子类型和颜色，并可在接口中关联现有耗材卷。</p></div><Card><CardContent><form onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate(form)}} className="grid sm:grid-cols-2 lg:grid-cols-7 gap-3"><input required placeholder="编码" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="input-stage7"/><input required placeholder="材料 PLA" value={form.material} onChange={e=>setForm({...form,material:e.target.value})} className="input-stage7"/><input placeholder="子类型" value={form.subtype||''} onChange={e=>setForm({...form,subtype:e.target.value})} className="input-stage7"/><input placeholder="品牌" value={form.brand||''} onChange={e=>setForm({...form,brand:e.target.value})} className="input-stage7"/><input placeholder="颜色名" value={form.color_name||''} onChange={e=>setForm({...form,color_name:e.target.value})} className="input-stage7"/><input type="color" value={form.color_hex||'#FFFFFF'} onChange={e=>setForm({...form,color_hex:e.target.value})} className="h-10 w-full bg-bambu-dark rounded"/><Button type="submit"><Plus size={16}/>新增</Button></form></CardContent></Card><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{data.map(m=><Card key={m.id}><CardContent><div className="flex justify-between"><span className="font-mono text-bambu-green">{m.code}</span><button className="text-red-400" onClick={async()=>{if(confirm('确认删除？被配方或耗材引用时系统会阻止删除。')){await materialsApi.remove(m.id);qc.invalidateQueries({queryKey:['material-types']})}}}><Trash2 size={17}/></button></div><div className="flex gap-3 mt-4 items-center"><span className="w-10 h-10 rounded-full border border-white/20" style={{background:m.color_hex||'#777'}}/><div><h2 className="text-white font-semibold">{m.brand||'未指定品牌'} · {m.material}{m.subtype?` ${m.subtype}`:''}</h2><p className="text-bambu-gray">{m.color_name||'未命名颜色'} · {m.color_hex||'无色值'}</p></div></div></CardContent></Card>)}</div><style>{`.input-stage7{background:#18181b;border:1px solid #3f3f46;border-radius:.5rem;padding:.5rem .75rem;color:white;min-width:0}`}</style></div>}
