import { useState } from 'react';
import type { FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MapPin, Plus, Trash2, Zap } from 'lucide-react';
import { productionRecipesApi, type PrinterProfile } from '../api/productionRecipes';
import { Button } from '../components/Button';
import { Card, CardContent } from '../components/Card';
const empty:Omit<PrinterProfile,'id'>={code:'',name:'',printer_model:'X1C',nozzle_diameter:.4,version:1,location:'',profile_group:'',auto_production_enabled:false,is_active:true};
export function PrinterProfilesPage(){const qc=useQueryClient();const {data=[]}=useQuery({queryKey:['printer-profiles'],queryFn:productionRecipesApi.profiles});const [form,setForm]=useState(empty);const create=useMutation({mutationFn:productionRecipesApi.createProfile,onSuccess:()=>{qc.invalidateQueries({queryKey:['printer-profiles']});setForm(empty)}});return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6"><div><h1 className="text-3xl font-bold text-white">打印配置组</h1><p className="text-bambu-gray mt-1">描述可用于生产的机型范围；开启“自动生产”也只保存资格，不会在第 7 阶段发起打印。</p></div><Card><CardContent><form onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate(form)}} className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><input required placeholder="配置编码" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="stage7-input"/><input required placeholder="显示名称" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="stage7-input"/><input required placeholder="机型，例如 X1C" value={form.printer_model} onChange={e=>setForm({...form,printer_model:e.target.value})} className="stage7-input"/><input type="number" min="0.1" step="0.1" value={form.nozzle_diameter} onChange={e=>setForm({...form,nozzle_diameter:Number(e.target.value)})} className="stage7-input"/><input placeholder="位置" value={form.location||''} onChange={e=>setForm({...form,location:e.target.value})} className="stage7-input"/><input placeholder="分组" value={form.profile_group||''} onChange={e=>setForm({...form,profile_group:e.target.value})} className="stage7-input"/><label className="text-white flex items-center gap-2"><input type="checkbox" checked={form.auto_production_enabled} onChange={e=>setForm({...form,auto_production_enabled:e.target.checked})}/>允许自动生产</label><Button type="submit"><Plus size={16}/>新增配置</Button></form></CardContent></Card><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{data.map(p=><Card key={p.id}><CardContent><div className="flex justify-between"><span className="font-mono text-bambu-green">{p.code} · v{p.version}</span><button className="text-red-400" onClick={async()=>{if(confirm('确认删除？被配方或板任务引用时系统会阻止删除。')){await productionRecipesApi.deleteProfile(p.id);qc.invalidateQueries({queryKey:['printer-profiles']})}}}><Trash2 size={17}/></button></div><h2 className="text-xl text-white font-semibold mt-3">{p.name}</h2><p className="text-bambu-gray">{p.printer_model} · {p.nozzle_diameter} mm 喷嘴</p><div className="flex gap-4 text-sm mt-4"><span className="text-bambu-gray flex gap-1"><MapPin size={16}/>{p.location||'未设位置'}</span><span className="text-bambu-gray">{p.profile_group||'未分组'}</span></div>{p.auto_production_enabled&&<div className="text-amber-300 mt-3 flex gap-2"><Zap size={16}/>已允许自动生产（尚未接调度）</div>}</CardContent></Card>)}</div><style>{`.stage7-input{background:#18181b;border:1px solid #3f3f46;border-radius:.5rem;padding:.5rem .75rem;color:white;min-width:0}`}</style></div>}
