import { useState } from 'react';
import type { FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Download, ImagePlus, Plus, Trash2 } from 'lucide-react';
import { productsApi } from '../api/products';
import { Button } from '../components/Button';
import { Card, CardContent, CardHeader } from '../components/Card';

export function ProductDetailPage(){
 const id=Number(useParams().id); const qc=useQueryClient(); const refresh=()=>qc.invalidateQueries({queryKey:['product',id]});
 const {data:p,isLoading}=useQuery({queryKey:['product',id],queryFn:()=>productsApi.get(id)}); const {data:components=[]}=useQuery({queryKey:['product-components'],queryFn:productsApi.components});
 const [componentForm,setComponentForm]=useState({code:'',name:'',unit:'pcs',description:'',is_active:true}); const [bom,setBom]=useState({component_id:0,quantity:1,notes:''});
 const addComponent=useMutation({mutationFn:productsApi.createComponent,onSuccess:()=>qc.invalidateQueries({queryKey:['product-components']})});
 const addBom=useMutation({mutationFn:()=>productsApi.addBom(id,bom),onSuccess:refresh});
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){await productsApi.uploadImage(id,f);refresh();}};
 if(isLoading||!p)return <div className="p-8 text-white">加载中…</div>;
 return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6"><Link to="/products" className="text-bambu-gray hover:text-white flex gap-2"><ArrowLeft size={18}/>返回产品列表</Link>
  <div className="flex flex-wrap justify-between gap-3"><div><div className="text-bambu-green font-mono">{p.sku}</div><h1 className="text-3xl font-bold text-white">{p.name}</h1><p className="text-bambu-gray">{p.description||'暂无说明'}</p></div><a href={productsApi.exportUrl(id)}><Button variant="secondary"><Download size={18}/>导出完整产品包</Button></a></div>
  <Card><CardHeader><div className="flex justify-between"><h2 className="text-xl font-semibold text-white">产品图片</h2><label className="cursor-pointer text-bambu-green flex gap-2"><ImagePlus size={18}/>上传图片<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={upload}/></label></div></CardHeader><CardContent>{!p.images?.length?<p className="text-bambu-gray">暂无图片（支持 PNG/JPEG/WebP，最大 10MB）</p>:<div className="grid grid-cols-2 md:grid-cols-5 gap-3">{p.images.map(x=><img key={x.id} src={productsApi.imageUrl(id,x.id)} alt={x.original_name} className="aspect-square object-cover rounded-lg bg-bambu-dark"/>)}</div>}</CardContent></Card>
  <Card><CardHeader><h2 className="text-xl font-semibold text-white">生产 BOM（每套产品用量）</h2></CardHeader><CardContent className="space-y-4"><form onSubmit={(e:FormEvent)=>{e.preventDefault();addBom.mutate()}} className="flex flex-wrap gap-3"><select required value={bom.component_id} onChange={e=>setBom({...bom,component_id:Number(e.target.value)})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 text-white"><option value={0}>选择组件</option>{components.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select><input type="number" min="0.001" step="0.001" value={bom.quantity} onChange={e=>setBom({...bom,quantity:Number(e.target.value)})} className="w-28 bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 text-white"/><input placeholder="备注" value={bom.notes} onChange={e=>setBom({...bom,notes:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 text-white"/><Button type="submit" disabled={!bom.component_id}><Plus size={16}/>加入 BOM</Button></form><div className="divide-y divide-bambu-dark-tertiary">{p.bom_items?.map(i=>{const c=components.find(x=>x.id===i.component_id);return <div key={i.id} className="flex justify-between py-3 text-white"><span>{c?.code} · {c?.name}</span><span>{i.quantity} {c?.unit}<button onClick={async()=>{await productsApi.deleteBom(id,i.id);refresh()}} className="ml-4 text-red-400"><Trash2 size={16}/></button></span></div>})}</div></CardContent></Card>
  <Card><CardHeader><h2 className="text-xl font-semibold text-white">组件库</h2></CardHeader><CardContent><form onSubmit={(e:FormEvent)=>{e.preventDefault();addComponent.mutate(componentForm)}} className="grid md:grid-cols-5 gap-3"><input required placeholder="组件编码" value={componentForm.code} onChange={e=>setComponentForm({...componentForm,code:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><input required placeholder="名称" value={componentForm.name} onChange={e=>setComponentForm({...componentForm,name:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><input placeholder="单位" value={componentForm.unit} onChange={e=>setComponentForm({...componentForm,unit:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><input placeholder="说明" value={componentForm.description} onChange={e=>setComponentForm({...componentForm,description:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><Button type="submit">新增组件</Button></form></CardContent></Card>
 </div>
}
