import { useState } from 'react';
import type { FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Download, ImagePlus, Plus, Trash2 } from 'lucide-react';
import { productsApi } from '../api/products';
import { productionRecipesApi } from '../api/productionRecipes';
import { Button } from '../components/Button';
import { Card, CardContent, CardHeader } from '../components/Card';

export function ProductDetailPage(){
 const id=Number(useParams().id); const qc=useQueryClient(); const refresh=()=>qc.invalidateQueries({queryKey:['product',id]});
 const {data:p,isLoading}=useQuery({queryKey:['product',id],queryFn:()=>productsApi.get(id)}); const {data:components=[]}=useQuery({queryKey:['product-components'],queryFn:productsApi.components});
 const {data:allRecipes=[]}=useQuery({queryKey:['production-recipes'],queryFn:productionRecipesApi.recipes});
 const {data:profiles=[]}=useQuery({queryKey:['printer-profiles'],queryFn:productionRecipesApi.profiles});
 const [componentForm,setComponentForm]=useState({code:'',name:'',unit:'pcs',description:'',is_active:true}); const [bom,setBom]=useState({component_id:0,quantity:1,notes:''});
 const [recipeForm,setRecipeForm]=useState({code:'',name:'',component_id:0,printer_profile_id:0});
 const addComponent=useMutation({mutationFn:productsApi.createComponent,onSuccess:()=>qc.invalidateQueries({queryKey:['product-components']})});
 const addBom=useMutation({mutationFn:()=>productsApi.addBom(id,bom),onSuccess:refresh});
 const addRecipe=useMutation({mutationFn:()=>productionRecipesApi.createRecipe({code:recipeForm.code,name:recipeForm.name,product_id:id,component_id:recipeForm.component_id,material_type_id:null,printer_profile_id:recipeForm.printer_profile_id||null,library_file_id:null,slicer_pipeline_id:null,slicer_preset:null,compatible_profile_ids:[],version:1,is_active:true}),onSuccess:()=>{qc.invalidateQueries({queryKey:['production-recipes']});setRecipeForm({code:'',name:'',component_id:0,printer_profile_id:0});}});
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){await productsApi.uploadImage(id,f);refresh();}};
 if(isLoading||!p)return <div className="p-8 text-white">加载中…</div>;
 return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6"><Link to="/products" className="text-bambu-gray hover:text-white flex gap-2"><ArrowLeft size={18}/>返回产品列表</Link>
  <div className="flex flex-wrap justify-between gap-3"><div><div className="text-bambu-green font-mono">{p.sku}</div><h1 className="text-3xl font-bold text-white">{p.name}</h1><p className="text-bambu-gray">{p.description||'暂无说明'}</p></div><a href={productsApi.exportUrl(id)}><Button variant="secondary"><Download size={18}/>导出完整产品包</Button></a></div>
  <Card><CardHeader><div className="flex justify-between"><h2 className="text-xl font-semibold text-white">产品图片</h2><label className="cursor-pointer text-bambu-green flex gap-2"><ImagePlus size={18}/>上传图片<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={upload}/></label></div></CardHeader><CardContent>{!p.images?.length?<p className="text-bambu-gray">暂无图片（支持 PNG/JPEG/WebP，最大 10MB）</p>:<div className="grid grid-cols-2 md:grid-cols-5 gap-3">{p.images.map(x=><img key={x.id} src={productsApi.imageUrl(id,x.id)} alt={x.original_name} className="aspect-square object-cover rounded-lg bg-bambu-dark"/>)}</div>}</CardContent></Card>
  <Card><CardHeader><div><h2 className="text-xl font-semibold text-white">产品零件清单</h2><p className="text-sm text-bambu-gray mt-1">填写制作 1 套这个产品分别需要哪些零件、每种零件需要几个。</p></div></CardHeader><CardContent className="space-y-4"><form onSubmit={(e:FormEvent)=>{e.preventDefault();addBom.mutate()}} className="flex flex-wrap gap-3"><select required value={bom.component_id} onChange={e=>setBom({...bom,component_id:Number(e.target.value)})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 text-white"><option value={0}>选择零件</option>{components.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select><input aria-label="每套需要数量" title="每套需要数量" type="number" min="0.001" step="0.001" value={bom.quantity} onChange={e=>setBom({...bom,quantity:Number(e.target.value)})} className="w-32 bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 text-white"/><input placeholder="备注（可不填）" value={bom.notes} onChange={e=>setBom({...bom,notes:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 text-white"/><Button type="submit" disabled={!bom.component_id}><Plus size={16}/>加入零件清单</Button></form><div className="divide-y divide-bambu-dark-tertiary">{p.bom_items?.map(i=>{const c=components.find(x=>x.id===i.component_id);return <div key={i.id} className="flex justify-between py-3 text-white"><span>{c?.code} · {c?.name}</span><span>每套需要 {i.quantity} {c?.unit}<button onClick={async()=>{await productsApi.deleteBom(id,i.id);refresh()}} className="ml-4 text-red-400"><Trash2 size={16}/></button></span></div>})}</div></CardContent></Card>
  <Card><CardHeader><div><h2 className="text-xl font-semibold text-white">零件打印方案</h2><p className="text-sm text-bambu-gray mt-1">每个零件至少建立一个打印方案，之后才能创建生产订单。本阶段只记录方案，不会启动打印。</p></div></CardHeader><CardContent className="space-y-4"><form onSubmit={(e:FormEvent)=>{e.preventDefault();addRecipe.mutate()}} className="grid md:grid-cols-5 gap-3"><input required placeholder="方案编号" value={recipeForm.code} onChange={e=>setRecipeForm({...recipeForm,code:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><input required placeholder="方案名称" value={recipeForm.name} onChange={e=>setRecipeForm({...recipeForm,name:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><select required value={recipeForm.component_id} onChange={e=>setRecipeForm({...recipeForm,component_id:Number(e.target.value)})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"><option value={0}>选择产品零件</option>{p.bom_items?.map(i=>{const c=components.find(x=>x.id===i.component_id);return <option key={i.component_id} value={i.component_id}>{c?.code} · {c?.name}</option>})}</select><select value={recipeForm.printer_profile_id} onChange={e=>setRecipeForm({...recipeForm,printer_profile_id:Number(e.target.value)})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"><option value={0}>暂不指定打印机配置</option>{profiles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button type="submit" disabled={!recipeForm.component_id||addRecipe.isPending}>新增打印方案</Button></form>{addRecipe.error&&<p className="text-red-400">{String(addRecipe.error)}</p>}<div className="divide-y divide-bambu-dark-tertiary">{allRecipes.filter(x=>x.product_id===id).map(x=>{const c=components.find(item=>item.id===x.component_id);return <div key={x.id} className="flex justify-between py-3 text-white"><span>{x.code} · {x.name}</span><span>{c?.name||'未关联零件'} · 版本 {x.version}</span></div>})}</div></CardContent></Card>
  <Card><CardHeader><div><h2 className="text-xl font-semibold text-white">可用零件</h2><p className="text-sm text-bambu-gray mt-1">先在这里建立零件，再把它加入上面的产品零件清单。</p></div></CardHeader><CardContent><form onSubmit={(e:FormEvent)=>{e.preventDefault();addComponent.mutate(componentForm)}} className="grid md:grid-cols-5 gap-3"><input required placeholder="零件编号" value={componentForm.code} onChange={e=>setComponentForm({...componentForm,code:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><input required placeholder="零件名称" value={componentForm.name} onChange={e=>setComponentForm({...componentForm,name:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><input placeholder="计数单位，例如：个" value={componentForm.unit} onChange={e=>setComponentForm({...componentForm,unit:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><input placeholder="零件说明（可不填）" value={componentForm.description} onChange={e=>setComponentForm({...componentForm,description:e.target.value})} className="bg-bambu-dark border border-bambu-dark-tertiary rounded-lg px-3 py-2 text-white"/><Button type="submit">新增零件</Button></form></CardContent></Card>
 </div>
}
